export const ADD_TO_CART = 'ADD_TO_CART'
export const UPDATE_CART_ITEMS = 'UPDATE_CART_ITEMS'
export const REMOVE_CART_ITEMS = 'REMOVE_CART_ITEMS'
export const REMOVE_ALL_CART_ITEMS = 'REMOVE_ALL_CART_ITEMS'